# Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and create a real matrix product.

In [1]:

import numpy as np
np.random.seed(99)
x=np.random.random((4,3))
x


array([[0.67227856, 0.4880784 , 0.82549517],
       [0.03144639, 0.80804996, 0.56561742],
       [0.2976225 , 0.04669572, 0.9906274 ],
       [0.00682573, 0.76979303, 0.7467671 ]])

In [2]:

y=np.random.random((3,4))
y

array([[0.37743894, 0.49414745, 0.92894839, 0.39545404],
       [0.9739563 , 0.52441472, 0.09361309, 0.81330841],
       [0.21168679, 0.55434578, 0.29226912, 0.81614236]])

In [3]:
res = np.dot(x,y)
res

array([[0.90385755, 1.04577   , 0.91146936, 1.33653512],
       [0.91860817, 0.75284008, 0.27016863, 1.13125377],
       [0.36751664, 0.72070745, 0.57037707, 0.96416703],
       [0.91040179, 0.8210309 , 0.29666042, 1.23824667]])

#Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

In [39]:

np1 = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'])
print(np1)

d1 = np.char.isdigit(np1)
l1 = np.char.islower(np1)
u1 = np.char.isupper(np1)
print("Digits only =", d1)
print("Lower cases only =", l1)
print("Upper cases only =", u1)


['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


#Write a program thatreads two space-separated positive integers X and Y as input and perform the following tasks:

In [13]:
lst1=[]
count=1
X=int(input("Enter a 1st list step size : "))
for i in range(1,200,X):
  if(count<=16):
    lst1.append(i)
    count+=1
  else:
    break
lst1


Enter a 1st list step size : 7


[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]

In [14]:
lst2=[]
count=1
Y=int(input("Enter a 2nd list step size : "))
for i in range(1,200,Y):
  if(count<=16):
    lst2.append(i)
    count+=1
  else:
    break
lst2

Enter a 2nd list step size : 9


[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]

In [15]:
np1=np.array(lst1)
np2=np.array(lst2)
print(np1)
print(np2)


[  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]
[  1  10  19  28  37  46  55  64  73  82  91 100 109 118 127 136]


In [16]:
np1.reshape((4,4))

array([[  1,   8,  15,  22],
       [ 29,  36,  43,  50],
       [ 57,  64,  71,  78],
       [ 85,  92,  99, 106]])

In [17]:
np2.reshape((4,4))

array([[  1,  10,  19,  28],
       [ 37,  46,  55,  64],
       [ 73,  82,  91, 100],
       [109, 118, 127, 136]])

In [20]:
np3=np.subtract(np1,np2)
print(np3)



[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of 
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).

In [33]:
np1=np.arange(1,10).reshape((3,3))
np2=np.linspace(1,21,9).reshape((3,3))


In [36]:
np3=np.subtract(np1,np2)
# np3.reshape((3,3))
print(np3)


[[  0.   -1.5  -3. ]
 [ -4.5  -6.   -7.5]
 [ -9.  -10.5 -12. ]]
